Server
Staffelhof/todoNOW pull request #3
Opened 2023-06-09 14:58 UTC by sibgatullin-i

2023-06-12 16:36 UTC, Staffelhof requested changes

2023-06-12 16:49 UTC, sibgatullin-i commented on server/express.js
> +  const indexHTML = fs.readFileSync(path.resolve(__dirname, './index.html'), {
мне без разницы, ни того, ни другого файла не было, когда я бранч создавал.

2023-06-12 16:58 UTC, sibgatullin-i commented on server/express.js
> +app.patch('/task/:id', (req, res) => {
принимается

2023-06-12 17:05 UTC, Staffelhof commented on server/express.js
> +  const indexHTML = fs.readFileSync(path.resolve(__dirname, './index.html'), {
собственно, dist - результат билда с кучей кодгена, на этапе разработки тащить в проект примерно также плохо, как и тащить node_modules

2023-06-12 17:18 UTC, Staffelhof commented on server/express.js
> +// const fs = require('fs');
файл сгенерируется и будет читаться

2023-06-12 17:19 UTC, Staffelhof commented on server/express.js
>  app.use('*', (req, res) => {
опять же, нет необходимости комментить этот кусок кода
достаточно вернуть переменной indexHTML путь на ../dist/index.html

2023-06-12 17:21 UTC, sibgatullin-i commented on server/express.js
>  app.use('*', (req, res) => {
эта часть из ветки main. кто и зачем это сделал - вопрос к тому, кто это сделал

2023-06-12 17:21 UTC, sibgatullin-i commented on server/express.js
> +// const fs = require('fs');
эта часть из ветки main. кто и зачем это сделал - вопрос к тому, кто это сделал

2023-06-12 17:22 UTC, Staffelhof commented on server/express.js
>  app.use('*', (req, res) => {
согласен, незачем ее комментить, раз это часть ветки main )

2023-06-12 17:23 UTC, Staffelhof commented on server/express.js
> +// const fs = require('fs');
согласен, незачем ее комментить, раз это часть ветки main )

2023-06-12 17:39 UTC, Staffelhof commented
make react-build и вся статика появится
недосмотрел, стоило расширить make server-start и для генерации статики

2023-06-15 08:12 UTC, Staffelhof submitted a review, later dismissed

2023-06-15 08:12 UTC, Staffelhof commented on server/express.js
> +// обслуживание статических ресурсов
это нужно раскомментировать

2023-06-15 08:12 UTC, Staffelhof commented on server/express.js
> +app.use('/html', express.static(path.join(__dirname, '../html')));
это не нужно, статика генерируется реактом в папку dist, после натягивания верстки на реакт эти файлы будут удалены

2023-06-16 05:48 UTC, merged